# Generated by Django 2.1.4 on 2018-12-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0002_auto_20181205_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='tweet',
        ),
    ]
