# Generated by Django 2.1.4 on 2018-12-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0003_auto_20181205_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='twitter_clone.TwitterUser'),
            preserve_default=False,
        ),
    ]
